twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # configure the Symfony application to use Bootstrap 4 styles when rendering forms
    form_themes: ['bootstrap_4_layout.html.twig']
